"""Agrega campo message en consultas

Revision ID: 5013137a4814
Revises: a3c1212997db
Create Date: 2025-05-29 13:35:00.806016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5013137a4814'
down_revision = 'a3c1212997db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True, comment='Mensaje enviado por el cliente'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###
