"""Agregar campos a la base de datos de consultas

Revision ID: 638074b3bef2
Revises: 9b4a7d4e5e4b
Create Date: 2025-06-09 10:46:58.883278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638074b3bef2'
down_revision = '9b4a7d4e5e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_reserva', sa.String(length=255), nullable=True, comment='Tipo de Reserva'))
        batch_op.add_column(sa.Column('fecha_reserva', sa.DateTime(), nullable=True, comment='Fecha en que se desea la reserva'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.drop_column('fecha_reserva')
        batch_op.drop_column('tipo_reserva')

    # ### end Alembic commands ###
