"""Agregar campos respuesta y atencion en consultas

Revision ID: 8b6b221466ed
Revises: 5013137a4814
Create Date: 2025-05-29 13:40:19.826405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6b221466ed'
down_revision = '5013137a4814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondida', sa.Boolean(), nullable=True, comment='Indica si la consulta ha sido respondida'))
        batch_op.add_column(sa.Column('admin_response', sa.Text(), nullable=True, comment='Respuesta del administrador'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.drop_column('admin_response')
        batch_op.drop_column('respondida')

    # ### end Alembic commands ###
