"""Initial migration

Revision ID: 96fff7626443
Revises: 
Create Date: 2025-05-21 07:35:10.045672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96fff7626443'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único de la oferta'),
    sa.Column('username', sa.String(length=80), nullable=True, comment='Nombre de usuario'),
    sa.Column('lastname', sa.String(length=80), nullable=True, comment='Apellido del usuario'),
    sa.Column('usermail', sa.String(length=120), nullable=False, comment='Correo electrónico del usuario'),
    sa.Column('phone_number', sa.String(length=24), nullable=True, comment='Teléfono'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='Contraseña del usuario'),
    sa.Column('role', sa.Enum('cliente', 'administrador', name='roleenum'), nullable=False, comment='Rol del usuario (cliente o administrador)'),
    sa.Column('birthday', sa.Date(), nullable=False, comment='Fecha de nacimiento'),
    sa.Column('dni', sa.String(length=20), nullable=True, comment='DNI'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='Direccion'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usermail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
