"""Agregar nuevas tablas

Revision ID: 9b4a7d4e5e4b
Revises: 8b6b221466ed
Create Date: 2025-05-29 13:57:12.392326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4a7d4e5e4b'
down_revision = '8b6b221466ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completado', sa.Boolean(), nullable=True, comment='Indica si fue completada la reserva'))

    with op.batch_alter_table('reservas_eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completado', sa.Boolean(), nullable=True, comment='Indica si fue completado el evento'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas_eventos', schema=None) as batch_op:
        batch_op.drop_column('completado')

    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_column('completado')

    # ### end Alembic commands ###
