"""Agregar nuevas tablas

Revision ID: a3c1212997db
Revises: fbeaecfb2bd1
Create Date: 2025-05-21 13:55:13.437308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c1212997db'
down_revision = 'fbeaecfb2bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único de la consulta'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Nombre del cliente que realiza la consulta'),
    sa.Column('usermail', sa.String(length=120), nullable=False, comment='Correo electrónico del cliente'),
    sa.Column('telefono', sa.String(length=24), nullable=True, comment='Teléfono de contacto'),
    sa.Column('direccion', sa.String(length=255), nullable=True, comment='Dirección del cliente'),
    sa.Column('ciudad', sa.String(length=100), nullable=True, comment='Ciudad del cliente'),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False, comment='Fecha y hora en que se registró la consulta'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habitaciones',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único de la habitación'),
    sa.Column('titulo', sa.String(length=150), nullable=False, comment='Nombre o tipo de la habitación'),
    sa.Column('descripcion', sa.Text(), nullable=True, comment='Descripción de la habitación'),
    sa.Column('imagen', sa.String(length=255), nullable=False, comment='Ruta de imagen de la habitación (ej: static/images/habitaciones/ejemplo.jpg)'),
    sa.Column('precio', sa.Float(), nullable=False, comment='Precio por noche'),
    sa.Column('disponible', sa.Boolean(), nullable=False, comment='Indica si la habitación está disponible'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lugares',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único del lugar'),
    sa.Column('titulo', sa.String(length=150), nullable=False, comment='Título o nombre del lugar'),
    sa.Column('descripcion', sa.Text(), nullable=True, comment='Descripción del lugar'),
    sa.Column('imagen', sa.String(length=255), nullable=False, comment='Ruta relativa de la imagen del lugar (ej: static/images/lugares/nombre.jpg)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas_eventos',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único de la reserva de evento'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Nombre del cliente que realiza la reserva'),
    sa.Column('usermail', sa.String(length=120), nullable=False, comment='Correo electrónico del cliente'),
    sa.Column('telefono', sa.String(length=24), nullable=True, comment='Teléfono de contacto'),
    sa.Column('tipo_evento', sa.Enum('boda', 'bautizo', 'cumpleaños', 'aniversario', 'corporativo', 'otros', name='tipoeventoenum'), nullable=False, comment='Tipo de evento'),
    sa.Column('fecha_evento', sa.Date(), nullable=False, comment='Fecha del evento'),
    sa.Column('numero_invitados', sa.Integer(), nullable=False, comment='Número estimado de invitados'),
    sa.Column('lugar_evento', sa.String(length=150), nullable=True, comment='Lugar o área reservada'),
    sa.Column('mensaje', sa.Text(), nullable=True, comment='Mensaje adicional o requerimientos especiales'),
    sa.Column('fecha_reserva', sa.DateTime(), nullable=False, comment='Fecha y hora en que se registró la reserva'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único de la reserva'),
    sa.Column('habitacion_id', sa.Integer(), nullable=False, comment='ID de la habitación reservada'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Nombre del cliente'),
    sa.Column('usermail', sa.String(length=120), nullable=False, comment='Correo electrónico del cliente'),
    sa.Column('fecha_entrada', sa.Date(), nullable=True, comment='Fecha de entrada'),
    sa.Column('fecha_salida', sa.Date(), nullable=True, comment='Fecha de salida'),
    sa.Column('fecha_reserva', sa.DateTime(), nullable=False, comment='Fecha en que se realizó la reserva'),
    sa.ForeignKeyConstraint(['habitacion_id'], ['habitaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    op.drop_table('reservas_eventos')
    op.drop_table('lugares')
    op.drop_table('habitaciones')
    op.drop_table('consultas')
    # ### end Alembic commands ###
