"""Agregar imagenes

Revision ID: b93481503751
Revises: 96fff7626443
Create Date: 2025-05-21 08:33:09.219333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93481503751'
down_revision = '96fff7626443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carousel_images',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único de la imagen'),
    sa.Column('image_path', sa.String(length=255), nullable=False, comment='Ruta relativa de la imagen (ej: static/images/carrusel/ejemplo.jpg)'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Descripción de la imagen'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carousel_images')
    # ### end Alembic commands ###
